  DISCOVER_PATH = 'https://api.themoviedb.org/3/discover/movie?api_key='
  SEARCH_PATH = 'https://api.themoviedb.org/3/search/movie?api_key='
  MOVIE_DETAILS_PATH = 'https://api.themoviedb.org/3/movie/'
  GENRE_PATH = 'https://api.themoviedb.org/3/genre/movie/list?api_key='
  TOP_PATH = 'https://api.themoviedb.org/3/movie/top_rated?api_key='
